### ISSUE TITLE
error "The process cannot access the file because it is being used by another process"

### ISSUE THREAD

**Issue by jorgheymans** [xolstice/protobuf-maven-plugin#30] opened 2017-07-14 07:47 UTC
Hi,

We are seeing this error sporadically in our builds

```
14:24:11 [ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile-custom (default) on project sdk: Unable to copy the file to c:\RC\Jenkins\workspace\sdk\shared\target\protoc-plugins: c:\RC\Jenkins\workspace\sdk\shared\target\protoc-plugins\protoc-3.1.0-windows-x86_64.exe (The process cannot access the file because it is being used by another process) -> [Help 1]
```

it does not happen all the time, and often a subsequent build will work fine but it's a bit annoying as you can understand.

the plugin is configured as such:

```
  <build>
    <extensions>
      <extension>
        <groupId>kr.motd.maven</groupId>
        <artifactId>os-maven-plugin</artifactId>
        <version>1.5.0.Final</version>
      </extension>
    </extensions>
    <plugins>
      <plugin>
        <groupId>org.xolstice.maven.plugins</groupId>
        <artifactId>protobuf-maven-plugin</artifactId>
        <version>0.5.0</version>
        <configuration>
          <protocArtifact>com.google.protobuf:protoc:${protobuf.version}:exe:${os.detected.classifier}</protocArtifact>
          <pluginId>grpc-java</pluginId>
          <pluginArtifact>io.grpc:protoc-gen-grpc-java:${grpc.version}:exe:${os.detected.classifier}
          </pluginArtifact>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>compile-custom</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```

**Comment by sergei-ivanov** [comment] 2017-07-18 23:38
I believe I have seen it a couple of times too and I suspect it is because of a virus scanner under Windows holding on to the file. However, I have an idea how to improve things when multiple plugin goals are being run in a sequence. I'll post an update when the new version is ready.

**Comment by jorgheymans** [comment] 2017-07-19 07:43
great thanks !

**Comment by clevertension** [comment] 2017-10-13 06:22
do it resolved now? i meet this issue too, when i open the IDE(eclipse, intellij idea), it will always complain this during maven cli build

**Comment by sergei-ivanov** [comment] 2017-10-15 04:04
I have committed a small change that I hope will fix the problem. Unfortunately, I cannot reproduce the problem on my current system, so I cannot tell if it's been fixed. Please give version 0.5.1 a try (I can see it's already been synced to Maven central).

**Closed as completed** 2017-10-15 04:05 UTC
Labels: 4 - Done, problem

**Comment by jorgheymans** [comment] 2017-11-20 14:39
FYI haven't had the error for a good while now across our environments, so it seems that your fix did the trick thanks !
